export const API_OPERATION_TYPES = Object.freeze({
  setup: 'query',
  status: 'query',
  uptimeStatus: 'query',
  dashboardModels: 'query',
  adminStatus: 'query',
  userAgreement: 'query',
  privacyPolicy: 'query',
  about: 'query',
  homePageContent: 'query',
  publicBroadcasts: 'query',
  pricing: 'query',
  perfMetricsSummary: 'query',
  perfMetrics: 'query',
  rankings: 'query',
  ratioConfig: 'query',
  workosLogin: 'mutation',
  workosLogout: 'mutation',
  userGroups: 'query',
  selfGroups: 'query',
  self: 'query',
  inbox: 'query',
  inboxUnreadCount: 'query',
  markInboxItemRead: 'mutation',
  markAllInboxRead: 'mutation',
  userModels: 'query',
  generateAccessToken: 'mutation',
  affCode: 'query',
  topupInfo: 'query',
  userTopups: 'query',
  topup: 'mutation',
  stripePay: 'mutation',
  stripeAmount: 'mutation',
  affTransfer: 'mutation',
  updateSelf: 'mutation',
  deleteSelf: 'mutation',
  updateUserSetting: 'mutation',
  checkinStatus: 'query',
  checkin: 'mutation',
  users: 'query',
  adminBroadcasts: 'query',
  createBroadcast: 'mutation',
  deleteBroadcast: 'mutation',
  adminTopups: 'query',
  completeTopup: 'mutation',
  searchUsers: 'query',
  user: 'query',
  manageUser: 'mutation',
  updateUser: 'mutation',
  deleteUser: 'mutation',
  subscriptionPlans: 'query',
  subscriptionSelf: 'query',
  updateSubscriptionPreference: 'mutation',
  subscriptionStripePay: 'mutation',
  adminSubscriptionPlans: 'query',
  createSubscriptionPlan: 'mutation',
  updateSubscriptionPlan: 'mutation',
  updateSubscriptionPlanStatus: 'mutation',
  bindSubscription: 'mutation',
  userSubscriptions: 'query',
  createUserSubscription: 'mutation',
  invalidateUserSubscription: 'mutation',
  deleteUserSubscription: 'mutation',
  options: 'query',
  optionRevisions: 'query',
  updateOption: 'mutation',
  channelAffinityCache: 'query',
  clearChannelAffinityCache: 'mutation',
  resetModelPrices: 'mutation',
  performanceStats: 'query',
  clearDiskCache: 'mutation',
  resetPerformanceStats: 'mutation',
  forceGC: 'mutation',
  syncableChannels: 'query',
  fetchUpstreamRatios: 'mutation',
  channels: 'query',
  searchChannels: 'query',
  channelModels: 'query',
  enabledChannelModels: 'query',
  channel: 'query',
  channelKey: 'mutation',
  testAllChannels: 'mutation',
  testChannel: 'mutation',
  updateAllChannelBalance: 'mutation',
  updateChannelBalance: 'mutation',
  createChannel: 'mutation',
  updateChannel: 'mutation',
  deleteDisabledChannels: 'mutation',
  disableTagChannels: 'mutation',
  enableTagChannels: 'mutation',
  editTagChannels: 'mutation',
  deleteChannel: 'mutation',
  deleteChannels: 'mutation',
  fixChannelsAbilities: 'mutation',
  fetchUpstreamModels: 'mutation',
  fetchModels: 'mutation',
  batchSetChannelTag: 'mutation',
  tagModels: 'query',
  copyChannel: 'mutation',
  manageMultiKeys: 'mutation',
  applyChannelUpstreamUpdates: 'mutation',
  applyAllChannelUpstreamUpdates: 'mutation',
  detectChannelUpstreamUpdates: 'mutation',
  detectAllChannelUpstreamUpdates: 'mutation',
  tokens: 'query',
  searchTokens: 'query',
  token: 'query',
  tokenKey: 'mutation',
  createToken: 'mutation',
  updateToken: 'mutation',
  deleteToken: 'mutation',
  deleteTokens: 'mutation',
  tokenKeysBatch: 'mutation',
  redemptions: 'query',
  searchRedemptions: 'query',
  redemption: 'query',
  createRedemption: 'mutation',
  updateRedemption: 'mutation',
  deleteInvalidRedemptions: 'mutation',
  deleteRedemption: 'mutation',
  logs: 'query',
  deleteHistoryLogs: 'mutation',
  logsStat: 'query',
  logsSelfStat: 'query',
  channelAffinityUsageCache: 'query',
  userLogs: 'query',
  quotaDates: 'query',
  quotaDatesByUser: 'query',
  quotaDatesSelf: 'query',
  groups: 'query',
  prefillGroups: 'query',
  createPrefillGroup: 'mutation',
  updatePrefillGroup: 'mutation',
  deletePrefillGroup: 'mutation',
  vendors: 'query',
  searchVendors: 'query',
  vendor: 'query',
  createVendor: 'mutation',
  updateVendor: 'mutation',
  deleteVendor: 'mutation',
  syncUpstreamPreview: 'query',
  syncUpstreamModels: 'mutation',
  missingModels: 'query',
  modelsMeta: 'query',
  searchModelsMeta: 'query',
  modelMeta: 'query',
  createModelMeta: 'mutation',
  updateModelMeta: 'mutation',
  deleteModelMeta: 'mutation',
});

export const API_OPERATIONS = Object.freeze(
  Object.keys(API_OPERATION_TYPES).reduce((operations, operation) => {
    operations[operation] = operation;
    return operations;
  }, {}),
);

export function getAPIOperationType(operation) {
  const operationType = API_OPERATION_TYPES[operation];
  if (!operationType) {
    throw new Error(`Unknown GraphQL API operation: ${operation}`);
  }
  return operationType;
}

export function buildGraphQLDocument(operation) {
  const operationType = getAPIOperationType(operation);
  const documentName = operation
    .replace(/^[a-z]/, (char) => char.toUpperCase())
    .replace(/[^_0-9A-Za-z]/g, '');
  return `${operationType} ${documentName}($input: JSON, $params: JSON) {
  ${operation}(input: $input, params: $params)
}`;
}
